### ISSUE TITLE
ipc::chan发送消息要100ms

### ISSUE THREAD

**Issue by kipade** [mutouyun/cpp-ipc#10]
首先，我被这个代码惊艳到了，扫了一眼这个代码之后我想好好学学C++的新标准语法了，奈何能力有限，目前为止还看不懂。我现在试了试消息发送，我使用多对多的ipc::chan, 发现，调用它的send方法，要用掉100ms,我的系统是Linux 64位，酷睿8代i9, 32GB DDR4
期待您的回复。然后，我也会好好学习一下，谢谢

**Comment by kipade** [comment]
大概找到地方了，但是还是不明白为什么要这样，就是那个broadcast函数要等100ms,希望能够解惑。感谢

**Comment by mutouyun** [comment]
等100ms指的是每条消息吗？

我在[全局常量定义](https://github.com/mutouyun/cpp-ipc/wiki/%E5%85%A8%E5%B1%80%E5%B8%B8%E9%87%8F%E5%AE%9A%E4%B9%89)里有关于`default_timeout`的解释，若消息接收不及时导致收发队列被填满，后续的消息就不得不等待100ms，超时后会覆盖之前的消息导致丢包。

**Comment by kipade** [comment]
谢谢回复。我在发完消息我就看到那个broadcast里面的超时时间是100ms,在这里导致的整个延迟。不过，我还是希望这个精致的代码有个设计上的描述文档。
再次感谢

**Comment by mutouyun** [comment]
恩。。我想过支持低版本C++，比如C++11，其实相对简单。但要支持C++98/03，很多地方的写法就要调整了。

关于clock_gettime调用的问题，你可以把你认为合理的代码在这里提交给我，我可以考虑合并进去。

**Comment by kipade** [comment]
我今天专门去学了一下C++11，然后看这个代码就相对容易了，刚开始看，还有许多地方是要了解的。今天发现一个问题：当只有自己一个客户端时，有问题：运行两次，第一次运行第一次发送会有100ms超时问题，然后，就正常了，马上发送成功；第二次运行的时候，第一次还是超时，然后，接收好像是卡死了，调用栈显示卡死在接收线程的recv。附运行日志输出：
`kipade@darkstar:~/cppipc/bin/Debug$ ./cppipc 
201402
c0 is ready.
s
force_push: msg_id = 0, remain = -58, size = 6
force_push: k = 0, cc = 1, rc = 0
101ms taken to send
s
0ms taken to send
s
0ms taken to send
s
0ms taken to send
s
0ms taken to send
s
0ms taken to send

s
0ms taken to send
d
0ms taken to send
q
0ms taken to send
receiver quit...
kipade@darkstar:~/cppipc/bin/Debug$ ./cppipc 
201402
c0 is ready.
q
force_push: msg_id = 0, remain = -58, size = 6
101ms taken to send

d
d
sadf
sdf`

**Comment by kipade** [comment]
> 恩。。我想过支持低版本C++，比如C++11，其实相对简单。但要支持C++98/03，很多地方的写法就要调整了。
> 
> 关于clock_gettime调用的问题，你可以把你认为合理的代码在这里提交给我，我可以考虑合并进去。
关于这个clock_gettime的，它本来就是一系统调用，我一般用gettimeofday,精度满足要求，性能比那个clock_gettime要好(一般也可能没啥感觉)

**Comment by mutouyun** [comment]
这是因为你之前有一次意外退出（比如杀死进程），导致chat在退出时未清理共享内存的标记，使得后续创建的新chat实例以为之前那个chat还存在引起超时。

复现步骤：
1、重启电脑（或linux下用rm把shm删干净）
2、运行chat一次，直接退出（比如kill，或叉掉，不用q退出）
3、再运行chat一次，一直发送，直到显示出现如下内容：
```
c1 send: [255] l
l
c1 send: [256] l
l
c1 send: [257] l
force_push: msg_id = 613, remain = -58, size = 6
force_push: k = 0, cc = 2, rc = 1
```
4、此时新运行的chat都会出现问题。

你那边出现第一次超时，后续正常，按目前的逻辑是尝试清理无效connection成功了，但后面还是出现收发问题……看来超时的force_push有bug。

我这边多测试一下，研究下具体原因。

仅使用共享内存的ipc，多对对情况下在遇到异常退出时不怎么好处理。因为共享内存并不知道某个实例已经死了，而广播的逻辑又要求所有接收者都需要收到消息（尽量不丢包）。

我看到有些ipc库使用了socket辅助共享内存判断客户端是否已退出，后面如果问题严重，我可能也会考虑添加类似的做法。

**Comment by kipade** [comment]
事实上，你这个共享内存用的是posix的接口，都是有名字的，所以我每次运行都是先确保连接都没有了。如果正常最后一个进程退出的话，/dev/shm下就没有其它共享对象文件了。至少你能看到我上面的测试日志上可以看出，前一次的执行也是正常退出的

**Comment by kipade** [comment]
今天我刚开机，我发现了，第一次执行，顺利退出，然后，每隔一次就会出现第一个100ms超时问题，必现

**Comment by mutouyun** [comment]
什么叫每隔一次？
每次都是正常退出，连续这样做几次以后也会出现么？

**Comment by mutouyun** [comment]
ok，我重现出来了。

我正在修改channel连接的部分，可以保证每个receiver持有的connect-id都是唯一的，这样就避免了单纯引用计数时无法确定无效连接的问题了。

但这样改暂时有个缺点，就是每个chan只能最多32个连接（也就是receiver只能有32个）。

**Comment by mutouyun** [comment]
我改了一版，代码已提交。
send卡死的原因是意外退出导致waiter对象内部的锁没及时释放，引起进程死锁。

**Comment by kipade** [comment]
谢谢。我想我得持续学习这个代码，里面用了太多的新标准语法。我在GCC9.2上做了微调使用-std=stdc++11可以编译过去了。但是在嵌入式上使用linaro4.7(201303版)又冒出来太多问题了，估计得放弃。

**Comment by mutouyun** [comment]
GCC9.2？这么新的版本不用改啊。
你加了-std=c++14 或 -std=c++17 吗？
[C++ Standards Support in GCC - GNU Project - Free Software Foundation (FSF)](https://gcc.gnu.org/projects/cxx-status.html)

**Comment by mutouyun** [comment]
linaro4.7是老了点。我这边试过的最低版本是 arm-linux-gnueabihf-gcc 4.9.2 (20140904)

**Comment by kipade** [comment]
> GCC9.2？这么新的版本不用改啊。
> 你加了-std=c++14 或 -std=c++17 吗？
> [C++ Standards Support in GCC - GNU Project - Free Software Foundation (FSF)](https://gcc.gnu.org/projects/cxx-status.html)

我知道的啊，这个不怪GCC，我是说，我要使用std=C++11的话小调一下就能在9.2下使用

**Comment by kipade** [comment]
> linaro4.7是老了点。我这边试过的最低版本是 arm-linux-gnueabihf-gcc 4.9.2 (20140904)

你这个版本比我早一年哇。
