### ISSUE TITLE
receiver接收时sleep时间大于sender的发送间隔，会接收中断

### ISSUE THREAD

**Issue by weshao** [mutouyun/cpp-ipc#103]
[send_recv](https://github.com/mutouyun/cpp-ipc/tree/master/demo/send_recv)示例里面do_recv如果在while最后sleep一段超过发送间隔的时间，在接收10多个数据后，就会出现接收中断。请问接收端是有什么使用限制吗？

**Comment by mutouyun** [comment]
咱们邮件已经ok了吧？这个可以关了吧~？

**Comment by weshao** [comment]
已通过邮件沟通解决，感谢作者～
