### ISSUE TITLE
No ipc communication between gui(logged in user) and windows services(Local system account)

### ISSUE THREAD

**Issue by jayprakashkumar1** [mutouyun/cpp-ipc#105]
I have used cpp-IPC between two processes running in a logged-in user session.
but when I try to use the same in GUI and Windows services running as a local system account then no communication happens. Simply client-side sending failed.

I know services run in different sessions (session 0) isolated from logged user sessions. 

So I tried changing the Security **SECURITY_ATTRIBUTES** while creating **CreateFileMapping** to allow cross-session ipc communication but it still doesn't work.
I don't understand why it still not working.
There might be something that I am doing wrong here.

I have tried changing SECURITY_ATTRIBUTES this way:
File: cpp-ipc\src\libipc\platform\win\get_sa.h

```
inline LPSECURITY_ATTRIBUTES get_sa() {
    static struct initiator {

        //SECURITY_DESCRIPTOR sd_;
        SECURITY_ATTRIBUTES sa_;

        bool succ_ = false;

        initiator() {
       
            // Create a security descriptor that allows access to users in other sessions
            ZeroMemory(&sa_, sizeof(sa_));
            sa_.nLength = sizeof(sa_);
            if(!ConvertStringSecurityDescriptorToSecurityDescriptor(
            L"D:P(A;OICI;GA;;;SY)(A;OICI;GA;;;BA)(A;OICI;GWGR;;;IU)",
            SDDL_REVISION_1,
            &sa_.lpSecurityDescriptor,
            NULL)){
                ipc::error("fail ConvertStringSecurityDescriptorToSecurityDescriptor[%d]\n", static_cast<int>(::GetLastError()));
                return;
            } 
 
            sa_.nLength = sizeof(SECURITY_ATTRIBUTES);
            sa_.bInheritHandle = FALSE;
            succ_ = true;

            /*   
                **THE OLD CODE IS BELOW**
            */

            // if (!::InitializeSecurityDescriptor(&sd_, SECURITY_DESCRIPTOR_REVISION)) {
            //     ipc::error("fail InitializeSecurityDescriptor[%d]\n", static_cast<int>(::GetLastError()));
            //     return;
            // }
            // if (!::SetSecurityDescriptorDacl(&sd_, TRUE, NULL, FALSE)) {
            //     ipc::error("fail SetSecurityDescriptorDacl[%d]\n", static_cast<int>(::GetLastError()));
            //     return;
            // }
            // sa_.nLength = sizeof(SECURITY_ATTRIBUTES);
            // sa_.bInheritHandle = FALSE;
            // sa_.lpSecurityDescriptor = &sd_;
            // succ_ = true;
        }
    } handle;
    return handle.succ_ ? &handle.sa_ : nullptr;
}
```

Why is it not working between cross-session like GUI & service?

Please, please. @mutouyun 
Thanks a lot  :)

**Comment by mutouyun** [comment]
I think your problem is the same as [Issue 83](https://github.com/mutouyun/cpp-ipc/issues/83).

Regarding the communication difficulties caused by permission issues on Windows, it is indeed difficult to change on the current ipc mechanism. Maybe I need to add a read-only channel for low access visitors.

**Comment by jayprakashkumar1** [comment]
So Is there any plan to add this feature so that the service(Running as a Local system account) can also communicate to user mode and vice versa?
This is indeed a needed one for service and GUI communication.

**Comment by mutouyun** [comment]
I expect to solve such problems on the refactoring branch.

**Comment by jayprakashkumar1** [comment]
I think if we use Global in createFileMapping then cross session process can access it.
StackOverflow link: 
[https://stackoverflow.com/questions/43802058/using-file-mapping-in-different-sessions-on-windows](URL)

please review it @mutouyun 
Thanks a lot :)

**Comment by jayprakashkumar1** [comment]
I have also checked if the admin account or system account creates shared memory in **Global\\**  space then any process from any session can access that shared memory.

This is what I need in order to communicate between GUI(standard account) and service(Local system account)

Please reply soon.

**Comment by mutouyun** [comment]
Okay, I'll check it out this weekend. Could you please help me review the pr when the time comes?

**Comment by jayprakashkumar1** [comment]
Thanks and yes definitely I will do . Please try to do as soon as possible.

Thanks a lot

**Comment by mutouyun** [comment]
I have submitted a pr https://github.com/mutouyun/cpp-ipc/pull/106 for this issue, please review it when you are free, thank you~

**Comment by jayprakashkumar1** [comment]
I have commented regarding this making **Global\\** Please check it [https://github.com/mutouyun/cpp-ipc/pull/106#issuecomment-1732267130](url)

Thanks :) 
@mutouyun
