### ISSUE TITLE
libipc/semaphore.h may cause conflict while including thread

### ISSUE THREAD

**Issue by wangjunbo4** [mutouyun/cpp-ipc#114]
C++标准库里有同名文件semaphore.h，在include thread之后，如果同时引入libipc会报编译错误，需要更改libipc里semaphore.h的文件名。

**Comment by mutouyun** [comment]
咦，你这个不太对劲啊，我所有的头文件使用都是这样的：
```c++
#include "libipc/semaphore.h"
```
前面加了目录前缀不可能出问题啊，你是不是编译include路径不对，不应该include到libipc目录下面

**Comment by wangjunbo4** [comment]
奥，可能是我把include目录更改了，那这个应该是我使用方法的问题，谢谢
