### ISSUE TITLE
整体实现思路，文档

### ISSUE THREAD

**Issue by cy2333ytu** [mutouyun/cpp-ipc#119]
您好，可以提供一份项目实现的简单文档或者思路吗，小白自己理不清思路 :)

**Comment by mutouyun** [comment]
其实核心就是这个文件：src/libipc/prod_cons.h，这里面的策略都是各种定长无锁队列。
然后对于大内存，在队列中只存一个索引号，然后通过索引去取真正的内存。

**Comment by mutouyun** [comment]
麻烦的是没数据的时候怎么等待，这个位置不能忙等，所以不是无锁的。
