### ISSUE TITLE
不同用户进程通信的问题

### ISSUE THREAD

**Issue by yongchengzhang** [mutouyun/cpp-ipc#13]
稍微看了下平台相关的部分源码，windows平台下，不同用户进程的通信应该是有权限问题的，比如：SYSTEM用户的进程，与administrator用户的进程。

**Comment by mutouyun** [comment]
嗯，确实应该是的，我没做权限方面的控制。
你的使用上有这方面的需求么？

**Comment by yongchengzhang** [comment]
有这样的场景的使用需求的，按照现有代码来看，应该只能支持同一用户权限的进程下的通信，具体改进方式请参考：https://blog.csdn.net/u013105439/article/details/53271519

**Comment by mutouyun** [comment]
好的，谢谢。
有空我调整下代码。

**Comment by mutouyun** [comment]
19f471b
