### ISSUE TITLE
关于代码风格问题

### ISSUE THREAD

**Issue by sshsu** [mutouyun/cpp-ipc#14]
虽然在issue下面提出这个问题非常不合适，但是cpp-ipc是一个很好的项目，衷心的希望大家能够一起参与进来讨论学习，所以提起勇气提一个这样的疑惑，我个人c++写的不算多，但是说实在感觉看作者的这个库看起来非常吃力，可能是为了优美很扩展性，很多东西都做了分离，抽象，包装，但是看起来很晦涩，我个人感觉这样的代码风格是否不太友好，是否在工程上不太适合这么写，只是因为这是一个私人开发的库所以这么写吗？

比如，对于下面一个这样的send函数，如果想知道大概做什么，看调用的名字就很清楚，但想要看清楚一些别的东西，比如是怎么发消息的，大文件怎么处理的，怎么同步的，怎么通知等等，这些就要往下面看，但是这种结构往下面看很难受，这18行里面用了4个lambda表达式，就需要带着记忆跳回来看很累，这比直接看会反人类不少(这也可能是因为我本人lambda表达式用的不多的关系不太喜欢这样)；其次在这种结构下，为了扩展性，就必须用auto，auto 虽然能自动推导也很好用，但是用多了，对于代码的阅读性而言，是很受影响的，auto通常都只是在一些明显能看到什么类型的地方使用，不清楚各位用什么看代码，我本人用的是vscode，vscode的定义跳转已经算是好的了，但是这种auto变量的调用是完全没法跳转的，没法直接跳转很多时候就需要手动搜
，一些vim党通常也没有配置ycm这么重的东西去看定义，使用简单的符号跳转，去看在这样的lambda下的auto变量一些调用的一定就更难了

```
static bool send(ipc::handle_t h, void const * data, std::size_t size) {
    return send([](auto info, auto que, auto msg_id) {  
        return [info, que, msg_id](std::int32_t remain, void const * data, std::size_t size) {
            if (!wait_for(info->wt_waiter_, [&] {
                    return !que->push(info->cc_id_, msg_id, remain, data, size);
                }, default_timeout)) {
                ipc::log("force_push: msg_id = %zd, remain = %d, size = %zd\n", msg_id, remain, size);
                if (!que->force_push([](void* p) {
                    auto tmp_msg = static_cast<typename queue_t::value_t*>(p);
                    if (tmp_msg->storage_) {
                        clear_storage(*reinterpret_cast<std::size_t*>(&tmp_msg->data_), 
                                      static_cast<std::int32_t>(data_length) + tmp_msg->remain_);
                    }
                    return true;
                }, info->cc_id_, msg_id, remain, data, size)) {
                    return false;
                }
            }
            info->rd_waiter_.broadcast();
            return true;
        };
    }, h, data, size);
}
```

谢谢

**Comment by mutouyun** [comment]
谢谢你的意见。

send函数包装了很多层，但每一层的目的是单一的。
你想搞清楚的这些细节问题，本就只有最底层的那个send才会有。
最底层的send可以理解为一个高阶函数，它的参数是对其内部细节做特化的“配置”，用了一些函数式编程的思想，常规的过程式、OOP式思想确实不好理解。

你可以想象一下，如果不用我现在的写法，把send用其他思想改写一下，应该写成什么样子，代码量大概是多大，性能是否会有提升。

其实这个代码并不难看懂，你在最上面的泛型send里搜索一下 gen_push 和 try_push 就知道这是要干啥了。

**Comment by sshsu** [comment]
原来这就是函数式编程，第一次看的这样的风格真的惊奇，大开眼界
