### ISSUE TITLE
库代码使用的C++语言标准是？

### ISSUE THREAD

**Issue by 3xLOGICKevinHan** [mutouyun/cpp-ipc#15]
编译这个库需要编译器支持的C++语言标准是什么？
C++11? C++14? C++17?

之所以问这个问题，是因为我使用的编译器是linaro-armv7ahf-2015.11-gcc5.2_v521.tar.xz。应该支持不到太高的C++语言标准。要是只需要支持C++11的话，应该没问题。

**Comment by mutouyun** [comment]
至少支持14。
gcc5.2可以支持C++14了，我测试的最低版本是4.9.2，你的编译器应该是没问题的。

**Comment by 3xLOGICKevinHan** [comment]
谢谢回复:) 我这边试试。

**Comment by 3xLOGICKevinHan** [comment]
能否请教一些代码中的技术问题?
我对C++11中的内存序一直没理解。我看这里的库代码很多地方使用了内存序。例如，
lc_.fetch_sub(1, std::memory_order_release);
auto cc_curr = cc_flag->load(std::memory_order_acquire);
...
能否请教下，我应该如何理解这里的代码？

**Comment by mutouyun** [comment]
手动设置内存序的目的是避免全序下的性能损失。毕竟不论是编译器优化还是CPU指令重排等，本质上都是为了优化性能。在保证正确性的前提下，我们应该尽量允许乱序。

内存序指的是CPU对内存的访问顺序。
但我们主要关注的是不同线程之间存在交互时，相互之间看到的内存访问时序。
对于单线程程序而言，内存序的设置一般来说是无意义的，因为编译器和CPU **必须** 保证单线程下的逻辑顺序和代码一致（哪怕乱序）。

C++ atomic 库默认使用最强一致性（memory_order_seq_cst），保证多线程下，所有线程观察到的内存顺序均一致。逻辑上的保证最强，但性能相对最低。其它内存序各自具有不同的保证，但都比 memory_order_seq_cst 弱。

你可以参考下这两篇文章：
- [内存顺序（Memory Order） - 知乎](https://zhuanlan.zhihu.com/p/45566448)
- [c++并发编程1.内存序 - 知乎](https://zhuanlan.zhihu.com/p/55901945)

**Comment by 3xLOGICKevinHan** [comment]
非常感谢！
之前查了很多相关的资料，都说不清楚这个feature出现的原因，要解决的是什么问题。你的解释让我茅塞顿开，至少理解了它的基本动机。虽然细节还需要我去详细探究。
我对C++11之后的语言新特性只有粗浅的理解，还得继续学习啊:)

**Comment by 3xLOGICKevinHan** [comment]
![image](https://user-images.githubusercontent.com/28504647/89487092-37a93d00-d7d7-11ea-9c4f-be7101666cd8.png)
这个是C++ programming language 4th edition中的一段。我不太理解。明明这里的x和x_init是全局变量。编译器应该假定它们可能被其它线程修改。所以应该很保守才对，就是说不会对init()中的2行代码重排序才读。怎么这里却说可能重排序呢？

**Comment by 3xLOGICKevinHan** [comment]
刚刚图片一致不能正确显示。现在好了:)

**Comment by mutouyun** [comment]
“编译器应该假定它们可能被其它线程修改”
你这个假定从哪里得出的？C/C++编译器只对单线程负责。
在没有标准内存序的情况下，C++ 98/03 对多线程之间的内存序没有任何假定。

**Comment by 3xLOGICKevinHan** [comment]
在C++11之前，我完全没有内存序的概念。甚至不知道有编译器乱序和CPU执行乱序这种东西。只是单纯的认为，代码会按照我的书写顺序执行。在多线程的情况下，唯一做的事情，就是保证共享的编码使用锁来避免数据竞争。在这种情况下，能保证我书写出来的代码不会产生由于指令重排导致的bug吗？
例如上面的代码，如果我将x_init改为atomic<boo>来避免数据竞争，同时使用std::memory_order_relaxed内存序。那么如果再加上下面的代码，
![Image 1](https://user-images.githubusercontent.com/28504647/89501037-41419d80-d7f5-11ea-81c7-898e21b7a60f.png)
那这份代码的正确性能得到保证吗？按照你的意思（以及似乎书中也是这个意思），线程1中init函数中的2行代码可能被调换顺序，而导致bug。即，Now we have a problem: thread 2 may never wait and thus will assign an uninitialized x to y.
可能在C++11之前，我觉得我确实会写出这种代码。因为我都不知道有编译器乱序和CPU执行乱序这种东西。

**Comment by mutouyun** [comment]
是的，多线程下不保证内存序（除非你主动指定）。
在 C++11 之前，标准没有多线程的任何工具（及保证）。你使用系统API去实现锁，API会自动帮你保证字节序（否则操作系统无法正确的支持多线程数据访问）。
