### ISSUE TITLE
windwos vs2019 X86 引用ipc.lib报错

### ISSUE THREAD

**Issue by panguclick** [mutouyun/cpp-ipc#18]
error LNK2019: 无法解析的外部符号 "__declspec(dllimport) public: static bool __cdecl ipc::chan_impl<struct ipc::wr<1,1,1> >::send(void *,void const *,unsigned int)" (__imp_?send@?$chan_impl@U?$wr@$00$00$00@ipc@@@ipc@@SA_NPAXPBXI@Z)，函数 "public: bool __thiscall ipc::chan_wrapper<struct ipc::wr<1,1,1> >::send(void const *,unsigned int)" (?send@?$chan_wrapper@U?$wr@$00$00$00@ipc@@@ipc@@QAE_NPBXI@Z) 中引用了该符号

**Comment by lrh450330** [comment]
你这个看起来跟源码没有关系啊，你是不是用了静态方法使用呢

**Comment by panguclick** [comment]
是用的静态方法使用的

**Comment by panguclick** [comment]
ipc::channel tt{"", ipc::sender};
     tt.send(msg);
是用的静态库引入的方法使用的

**Comment by panguclick** [comment]
找到原因了，c++语言标准没设置成C++17
