### ISSUE TITLE
断开连接时崩溃

### ISSUE THREAD

**Issue by cetcjinjian** [mutouyun/cpp-ipc#23]
例子里面是这样写的 
ipc::route cc{"ipc"};
没问题

但是
char sz[] = {"ipc"};
ipc::route cc;
cc.connect(sz,ipc::sender);
当调用 cc.disconnect() 发生崩溃

**Comment by cetcjinjian** [comment]
程序结束时会调用 disconnect() , 手动调用的话会多调用一次，出现错误。

**Comment by mutouyun** [comment]
我记下来了，有空看下能不能忽略多次disconnect的问题
