### ISSUE TITLE
是否考虑加入写入互斥

### ISSUE THREAD

**Issue by cetcjinjian** [mutouyun/cpp-ipc#24]
如 demo中的 msg_que,
如果已经执行了一个 msg_que sender 再执行第二个 msg_que sender 时，提示错误，已经存在一个 sender 了。

**Comment by mutouyun** [comment]
你的意思是，在只允许单对单通讯的情况下，多个sender尝试连接时，让`que__.reconnect(ipc::sender)`返回`false`吗？

**Comment by cetcjinjian** [comment]
> 你的意思是，在只允许单对单通讯的情况下，多个sender尝试连接时，让`que__.reconnect(ipc::sender)`返回`false`吗？

是的，通过配置文件生成sender的话，如果配置文件不小心填错了，可能造成多个 sender往同一个 receiver发送数据

**Comment by mutouyun** [comment]
好的，我元旦的时候想想做法

**Comment by cetcjinjian** [comment]
在create sender的时候，是否有办法知道已经create 了同名的 sender？ 之前使用另一套 shmget（key...），如果已经有key地址被打开了 ，那就返回创建失败

**Comment by mutouyun** [comment]
可以做，只是我现在的ipc接口上没有这个试探的逻辑。
因为对于mpmc（多发多收）来说，没必要试探，所以需要对不同的策略做区分，而这个分派逻辑目前是没有的。
当前的策略主要还是影响 prod_cons_impl 的实现选择。

你的建议我考虑下怎么改。

**Comment by mutouyun** [comment]
我改了一些问题，并合入了你的需求。
详见 pull requests #25

如果你review发现了问题，或者在release分支上测试发现了问题，还请及时告诉我一声，谢谢~

**Comment by cetcjinjian** [comment]
> 我改了一些问题，并合入了你的需求。
> 详见 pull requests #25
> 
> 如果你review发现了问题，或者在master分支上测试发现了问题，还请及时告诉我一声，谢谢~

好的，好快呀
