### ISSUE TITLE
請問目前x86和x64之間是不是不能溝通?

### ISSUE THREAD

**Issue by intere2960** [mutouyun/cpp-ipc#3]
您好，如題，我目前寫了兩個process分別是x86和x64，原本一直想說為何無法溝通成功，後來實驗發現好像只能兩個process要在同cpu架構才能work，想問是不是這是現在這個tool的限制? (我用提供的demo chat也不行)

**Comment by mutouyun** [comment]
你的机器是异构处理器么？还是说是两台机器？

**Comment by intere2960** [comment]
我是兩個process(一個x86, 一個x64)，這樣的狀況下好像目前無法傳遞資料，我是起來一定要都是x86 or x64才行。

**Comment by mutouyun** [comment]
我确认一下，你的设备是两个process，在一个mainboard上是吗？
如果两个process都是相同的32位或64位，之间的ipc是ok的对吗？

如果两个process的体系不同，那么它们之间的alignof(std::max_align_t)、sizeof(void*)以及std::size_t都会不一样，这会导致对同一块共享内存的解析出现不一致，从而导致无法正常通讯。

建议你在x64的核上编译和运行x86版本。

**Comment by intere2960** [comment]
我的cpu是x64，但是我目前的應用需要再同一台機器上同時運行x64和x86的process並互相傳遞資料，才會試到如果我把process build成都是x86或都是x64目前這個tool才能使用，因為在我的認知ipc應該要能支援x64<->x86溝通的這個使用情境才對(我不確定有沒有理解錯誤)。

**Comment by mutouyun** [comment]
如果是基于socket的ipc的话，会比较容易做。对于你的需求我需要修改下数据结构。
不过我没有和你那边类似的测试环境，所以我调整完之后应该还是需要你那边反复测试并反馈结果。

你那边的时间急么？

**Comment by intere2960** [comment]
我目前不急，目前先使用其他的windows api繼續完成我工作project的需求，只是想說你目前你的tool包裝得很方便，能多支援這種情境的話會更好，若有後續進度的話我會樂意幫忙測試。

**Comment by mutouyun** [comment]
好的，这个issue我先不关。有空的话我这两周先提交一个版本给你测试下

**Comment by mutouyun** [comment]
我今天简单调整了下ipc的数据结构，本地测试ok，不确定你的环境下是否改好了，你可以先测试下（master分支）。
还请及时告知我测试结果，谢谢。

**Comment by intere2960** [comment]
我的環境目前用最新的revision是可以使用的，感謝能這麼快更新我遇到的問題。

**Comment by pi1ot** [comment]
> 您好，如題，我目前寫了兩個process分別是x86和x64，原本一直想說為何無法溝通成功，後來實驗發現好像只能兩個process要在同cpu架構才能work，想問是不是這是現在這個tool的限制? (我用提供的demo chat也不行)

在同一台设备上的share memory通信才有意义吧，share memory怎么跨设备通信？

**Comment by intere2960** [comment]
> > 您好，如題，我目前寫了兩個process分別是x86和x64，原本一直想說為何無法溝通成功，後來實驗發現好像只能兩個process要在同cpu架構才能work，想問是不是這是現在這個tool的限制? (我用提供的demo chat也不行)
> 
> 在同一台设备上的share memory通信才有意义吧，share memory怎么跨设备通信？

你好, 我當初的意思是我同台機器build x86和x64的兩個process不能互相溝通, 不是不同台機器, 後續作者也已更新這部分功能
