### ISSUE TITLE
当consumer没收到数据时，一直阻塞

### ISSUE THREAD

**Issue by cetcjinjian** [mutouyun/cpp-ipc#30]
msq_queue的 demo里面

auto msg = que__.recv();当没有数据时，会一直阻塞在这里

可以设置不阻塞吗？

**Comment by mutouyun** [comment]
你可以试试 try_recv，数据没接到返回空 buff。另外，recv 接口有超时参数：
`buff_t recv(std::size_t tm = invalid_value)`
你可以在 tm 里填你希望的等待时间，单位 ms。

**Comment by cetcjinjian** [comment]
好的 谢谢
