### ISSUE TITLE
如何缩短延迟

### ISSUE THREAD

**Issue by cetcjinjian** [mutouyun/cpp-ipc#31]
测试系统 cpu 3.7g ，平均每次收发 1024字节的数据，延迟在 1.4us左右，可以进一步缩短延迟吗?

**Comment by cetcjinjian** [comment]
模式时 route = chan<relat::single, relat::multi, trans::broadcast>;

**Comment by cetcjinjian** [comment]
跟ipc没关系，应该是其它地方，系统上下文切换？

**Comment by mutouyun** [comment]
请问操作系统是？我实测发现windows的延迟比linux要高不少。

**Comment by cetcjinjian** [comment]
> 请问操作系统是？我实测发现windows的延迟比linux要高不少。

centos7.9 ，可能windows的系统中断或上下文要比linux 多吧
