### ISSUE TITLE
def.h中data_length的作用是?

### ISSUE THREAD

**Issue by cetcjinjian** [mutouyun/cpp-ipc#32]
// constants

enum : std::size_t {
    invalid_value   = (std::numeric_limits<std::size_t>::max)(),
    //data_length     = 1024,
    data_length     = 64,
    large_msg_limit = data_length,
    large_msg_cache = 32,
    default_timeout = 100 // ms
};

**Comment by mutouyun** [comment]
是队列中默认单个消息的大小。
如果超出这个大小，就会使用另外的内存池存放消息，队列中仅保存内存池id。

**Comment by cetcjinjian** [comment]
好的 谢谢，我的单条消息大小是1024，发现 设置data_length的大小 对速度没什么影响

**Comment by mutouyun** [comment]
嗯，是的，除非你关掉了 large_msg_cache，这样就会对大小超出 data_length 的数据进行拆包拼包动作。
