### ISSUE TITLE
Add a better disconnector per channel

### ISSUE THREAD

**Issue by Nader-Sl** [mutouyun/cpp-ipc#37]
For now the demo application relies on signal interception to run disconnect(), but I dont think that is very reliable and it doesn't seem to work with NAPI.

**Comment by mutouyun** [comment]
The disconnect which in signal interception is just a fail-safe protection, it's orthogonal to NAPI.
You could use other, more reliable methods to trigger the disconnect behavior without using signals.

**Comment by Nader-Sl** [comment]
hmm, and why isn't it designed by default to continue popping messages once the client reconnects since shared memory is accessed by name and in it can be a format with upfront bytes that save some states if needed?

**Comment by Nader-Sl** [comment]
decreasing the **large_msg_cache** to 5 seemed to fix the issue for missing out on disconnect call =/

**Comment by Nader-Sl** [comment]
I actually found it best to create a new heap instance of a class that wraps the channel/queue, and then periodically check the target process that interacts, if it is shutdown then delete and re-instantiate an instance which will call all the clearing destructors/cleanup.

**Comment by mutouyun** [comment]
This is a good idea, but it requires that you have a central node in your system that you can use to manage the life cycle of other nodes. And some schemes do use a similar approach, like dbus or something else.

**Comment by Nader-Sl** [comment]
@mutouyun I incorporate this in Windows meanwhile, and I already check if the target process I am communicating with is running or not in a separate thread every few second or so for a different purpose, so I thought on that end it is actually feasible to disconnect and delete the instance wrapper when its not found to be running, and then new it again when it runs again to re-establish sort of a connection, on the other side of the communication for the other producer in the other application I can afford handling a graceful disconnect without needing to use signals :)
