### ISSUE TITLE
这个有在生产环境中应用了么

### ISSUE THREAD

**Issue by FreeMind-LJ** [mutouyun/cpp-ipc#4]

**Comment by mutouyun** [comment]
我在自己公司的车载系统上用了

**Comment by mutouyun** [comment]
建议在2017上用。
我在appveyor的ci环境里用2015编译测试是正常的，如果实在编译不过去，你可以把
cpp-ipc/src/memory/resource.h：
```c++
template <typename T>
using allocator = allocator_wrapper<T, async_pool_alloc>;
```
这句改成这样：
```c++
template <typename T>
using allocator = std::allocator<T>;
```
即直接使用系统分配器。

**Comment by czhzng** [comment]
你好！按照上面修改后，有如下错误！类型转换问题！

c:\develop\cpp-ipc\src\pool_alloc.cpp(9): note: see reference to class template instantiation 'ipc::mem::static_wrapper<ipc::mem::variable_wrapper<ipc::mem::async_wrapper<ipc::mem::detail::fixed_alloc<ipc::mem::variable_alloc<1048576,ipc::mem::scope_alloc<ipc::mem::static_alloc>>,ipc::mem::fixed_expand_policy<4096,1048576>>,ipc::mem::default_recycler>,ipc::mem::static_alloc,ipc::mem::default_mapping_policy<0,4>>>' being compiled
1>c:\program files (x86)\microsoft visual studio 14.0\vc\include\xmemory0(876): error C2664: 'ipc::mem::allocator_wrapper<U,ipc::mem::limited_recycler<AllocP,true>::fixed_alloc_t<U>>::allocator_wrapper(const ipc::mem::allocator_wrapper<U,ipc::mem::limited_recycler<AllocP,true>::fixed_alloc_t<U>> &) noexcept': cannot convert argument 1 from 'std::_Wrap_alloc<ipc::mem::allocator_wrapper<U,ipc::mem::limited_recycler<AllocP,true>::fixed_alloc_t<U>>>' to 'ipc::mem::limited_recycler<AllocP,true>::fixed_alloc_t<U> &&'
1>          with
1>          [
1>              U=std::_Container_proxy,
1>              AllocP=ipc::mem::detail::fixed_alloc<ipc::mem::variable_alloc<1048576,ipc::mem::scope_alloc<ipc::mem::static_alloc>>,ipc::mem::fixed_expand_policy<4096,1048576>>
1>          ]
1>          and
1>          [
1>              U=std::_Tree_node<ipc::mem::detail::fixed_alloc<ipc::mem::variable_alloc<1048576,ipc::mem::scope_alloc<ipc::mem::static_alloc>>,ipc::mem::fixed_expand_policy<4096,1048576>>,void *>,
1>              AllocP=ipc::mem::detail::fixed_alloc<ipc::mem::variable_alloc<1048576,ipc::mem::scope_alloc<ipc::mem::static_alloc>>,ipc::mem::fixed_expand_policy<4096,1048576>>
1>          ]
1>          and
1>          [
1>              AllocP=ipc::mem::detail::fixed_alloc<ipc::mem::variable_alloc<1048576,ipc::mem::scope_alloc<ipc::mem::static_alloc>>,ipc::mem::fixed_expand_policy<4096,1048576>>,
1>              U=std::_Container_proxy
1>          ]

**Comment by mutouyun** [comment]
漏说了一个地方，resource.h里的async_pool_alloc改成这样：
```c++
using async_pool_alloc = static_alloc;
```
