### ISSUE TITLE
进程限制扩展

### ISSUE THREAD

**Issue by jinyuttt** [mutouyun/cpp-ipc#43]
这里限制32个进程，我在服务器使用，有没有办法扩展到64个甚至128个？

**Comment by mutouyun** [comment]
目前的版本来说，broadcast下是不行的，你用unicast是没限制的。
这个限制主要是对接收端来说的，因为broadcast需要接收者已完成的记录，单纯使用引用计数在进程crash的时候就完蛋了。

因为当前版本对进程crash的处理仍然不够好，我正在试验一些别的方法来解决这类问题，等我最近忙完了，我会尝试更新下做法，看能不能干掉这个限制。
