### ISSUE TITLE
options for set the linking static or shared

### ISSUE THREAD

**Issue by aiekick** [mutouyun/cpp-ipc#47]
Hello,

thanks for your library who is working very well

btw can you add an options in the CMakeList.txt for have shared or static linking for the lib ?

Thanks

**Comment by mutouyun** [comment]
It's a reasonable requirement. I'll make time for it.

**Comment by aiekick** [comment]
cool, thanks

**Comment by mutouyun** [comment]
See: cca4664e840c019c1656a02219ae6e0ee3b63e33

You could use the option LIBIPC_BUILD_SHARED_LIBS for building shared libraries.
The default value of this option is OFF.

**Comment by aiekick** [comment]
thank you very mush

**Comment by mutouyun** [comment]
The pull request has been merged to master.
