### ISSUE TITLE
进程同步机制

### ISSUE THREAD

**Issue by sqn175** [mutouyun/cpp-ipc#54]
mutouyun，你好，非常感谢你的开源分享。
因为没有找到相关文档，想请问一下关于进程间同步的问题：

1. 代码中`waiter_linux.h`用到了`pthread_mutex_t `，同时`prod_cons.h`用到了`std::atomic`；另外还实现了`ipc::spin_lock`。请问这三者是否都是用于进程同步的？如果是的话机制有什么区别吗？
2. 后续是否有更加详细的文档或者wiki以供参考学习？

非常感谢！

**Comment by mutouyun** [comment]
`pthread_mutex_t`和`atomic`的区别，网上资料很多。

简单来说，`pthread_mutex_t`是通过linux futex机制，由用户态和内核态合作实现的同步。当出现冲突时，是会进入内核态进行调度仲裁的。
`atomic`，一般来说是通过硬件指令实现变量的原子读写，避免多线程、多进程下并发导致的变量读写异常。这里的原子行为绝大部分情况下是通过硬件指令完成的，属于用户态行为。
`spin_lock`，是通过`atomic`实现的锁。lock的时候是不会进内核态的（当然循环次数太多了还是会sleep）。

所以可能会出现长时间等待的情况，应该使用`pthread_mutex_t`；
永远不需要等待，只需要避免争用导致的读写错误，应该使用`atomic`；
可能会出现很短时间的等待，希望尽量避免进入内核态，考虑使用`spin_lock`。

当然凡事也不绝对。实际中也是需要根据各自情况见招拆招的。
异步编程首先需要保证正确性，在正确的前提下再通过性能测试来找寻最合适的做法。

**Comment by sqn175** [comment]
谢谢回复，我理解在`cpp-ipc`中是合理联合使用了这三种方法来进行进程间同步，从而达到最优性能的。而不是单用一种机制比如`pthread_mutex_t`来简单的进行同步的。不知这样理解是否正确？

再次感谢！

**Comment by mutouyun** [comment]
是的，你没办法只用一种方法来实现功能的。
比如对方没有消息过来的时候，接收端不等待还能干啥呢？这个时候就必须进入内核态等待调度，否则在应用层死循环是非常不好的。
