### ISSUE TITLE
Compilation errors

### ISSUE THREAD

**Issue by tchernitski** [mutouyun/cpp-ipc#6]
Thanks for awesome lib!

I got some compilation error while trying to build, here is how one of them looked like (others were the same nature):
`........ In file included from /usr/include/c++/5/bits/stl_pair.h:59:0,
                 from /usr/include/c++/5/bits/stl_algobase.h:64,
                 from /usr/include/c++/5/bits/char_traits.h:39,
                 from /usr/include/c++/5/string:40,
                 from /home/42/cpp-ipc/src/platform/shm_linux.cpp:12:
/usr/include/c++/5/bits/move.h: In instantiation of ‘void std::swap(_Tp&, _Tp&) [with _Tp = ipc::mem::allocator_wrapper<char, ipc::mem::static_wrapper<ipc::mem::variable_wrapper<ipc::mem::async_wrapper<ipc::mem::detail::fixed_alloc<ipc::mem::variable_alloc<2097152ul>, ipc::mem::fixed_expand_policy<8192ul, 2097152ul> >, ipc::mem::default_recycler> > > >]’:
/usr/include/c++/5/bits/allocator.h:175:8:   required from ‘static void std::__alloc_swap<_Alloc, false>::_S_do_it(_Alloc&, _Alloc&) [with _Alloc = ipc::mem::allocator_wrapper<char, ipc::mem::static_wrapper<ipc::mem::variable_wrapper<ipc::mem::async_wrapper<ipc::mem::detail::fixed_alloc<ipc::mem::variable_alloc<2097152ul>, ipc::mem::fixed_expand_policy<8192ul, 2097152ul> >, ipc::mem::default_recycler> > > >]’
/usr/include/c++/5/bits/basic_string.tcc:67:50:   required from ‘void std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::swap(std::__cxx11::basic_string<_CharT, _Traits, _Alloc>&) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = ipc::mem::allocator_wrapper<char, ipc::mem::static_wrapper<ipc::mem::variable_wrapper<ipc::mem::async_wrapper<ipc::mem::detail::fixed_alloc<ipc::mem::variable_alloc<2097152ul>, ipc::mem::fixed_expand_policy<8192ul, 2097152ul> >, ipc::mem::default_recycler> > > >]’
/usr/include/c++/5/bits/basic_string.h:589:2:   required from ‘std::__cxx11::basic_string<_CharT, _Traits, _Alloc>& std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::operator=(std::__cxx11::basic_string<_CharT, _Traits, _Alloc>&&) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = ipc::mem::allocator_wrapper<char, ipc::mem::static_wrapper<ipc::mem::variable_wrapper<ipc::mem::async_wrapper<ipc::mem::detail::fixed_alloc<ipc::mem::variable_alloc<2097152ul>, ipc::mem::fixed_expand_policy<8192ul, 2097152ul> >, ipc::mem::default_recycler> > > >]’
/home/42/cpp-ipc/src/platform/shm_linux.cpp:80:15:   required from here
/usr/include/c++/5/bits/move.h:186:11: error: use of deleted function ‘constexpr ipc::mem::allocator_wrapper<char, ipc::mem::static_wrapper<ipc::mem::variable_wrapper<ipc::mem::async_wrapper<ipc::mem::detail::fixed_alloc<ipc::mem::variable_alloc<2097152ul>, ipc::mem::fixed_expand_policy<8192ul, 2097152ul> >, ipc::mem::default_recycler> > > >& ipc::mem::allocator_wrapper<char, ipc::mem::static_wrapper<ipc::mem::variable_wrapper<ipc::mem::async_wrapper<ipc::mem::detail::fixed_alloc<ipc::mem::variable_alloc<2097152ul>, ipc::mem::fixed_expand_policy<8192ul, 2097152ul> >, ipc::mem::default_recycler> > > >::operator=(const ipc::mem::allocator_wrapper<char, ipc::mem::static_wrapper<ipc::mem::variable_wrapper<ipc::mem::async_wrapper<ipc::mem::detail::fixed_alloc<ipc::mem::variable_alloc<2097152ul>, ipc::mem::fixed_expand_policy<8192ul, 2097152ul> >, ipc::mem::default_recycler> > > >&)’
       __a = _GLIBCXX_MOVE(__b); .......`

and I fixed it by adding:
https://github.com/tchernitski/cpp-ipc/commit/b7656870e191ebd9a0125043336309169894329d

**Comment by mutouyun** [comment]
thank you very much for your issue!
and I have patched it by 792a9b3339ff1de9a9e84163db0b61075c1161f0
