### ISSUE TITLE
在VS2015上编译有错误，是不是只能在VS2017上编译？

### ISSUE THREAD

**Issue by czhzng** [mutouyun/cpp-ipc#7]
在VS2015上编译有错误，是不是只能在VS2017上编译？
错误信息是：
1>c:\program files (x86)\microsoft visual studio 14.0\vc\include\xmemory0(876): error C2664: 'ipc::mem::allocator_wrapper<U,ipc::mem::limited_recycler<AllocP,true>::fixed_alloc_t<U>>::allocator_wrapper(const ipc::mem::allocator_wrapper<U,ipc::mem::limited_recycler<AllocP,true>::fixed_alloc_t<U>> &) noexcept': cannot convert argument 1 from 'std::_Wrap_alloc<ipc::mem::allocator_wrapper<U,ipc::mem::limited_recycler<AllocP,true>::fixed_alloc_t<U>>>' to 'ipc::mem::limited_recycler<AllocP,true>::fixed_alloc_t<U> &&'

_Originally posted by @czhzng in https://github.com/mutouyun/cpp-ipc/issues/4#issuecomment-547966921_

**Comment by mutouyun** [comment]
cpp-ipc/src/memory/resource.h：
```cpp
using async_pool_alloc = static_wrapper<variable_wrapper<async_wrapper<
    detail::fixed_alloc<
        variable_alloc                           <sizeof(void*) * 1024 * 256>, 
        fixed_expand_policy<sizeof(void*) * 1024, sizeof(void*) * 1024 * 256>
    >, 
    default_recycler >>>;

template <typename T>
using allocator = allocator_wrapper<T, async_pool_alloc>;
```
这句改成这样：
```cpp
using async_pool_alloc = static_alloc;

template <typename T>
using allocator = std::allocator<T>;
```
即直接使用系统分配器。

**Comment by czhzng** [comment]
编译通过了，谢谢！后面我再用VS2017试试，原来的写法！

**Comment by mutouyun** [comment]
我调整了下代码，在win7 + vs2015上编译通过了。
有机会的话你可以试下最新的代码是不是还有错误？

**Comment by czhzng** [comment]
你好，新的代码在WIN10 64+VS2015，上编译无问题。谢谢！
