### ISSUE TITLE
C/S架构，如何实现Client send后同步接收Server的返回结果

### ISSUE THREAD

**Issue by lxgsbqylbk** [mutouyun/cpp-ipc#77]
你好，刚发现这个库。
我的场景是多client，单server。
client可给server发送数据，可能是异步发送，也可能发送后同步等待server的返回结果。
阅读了下ipc.h，发现channel的send没有带结果返回，想问一下作者推荐这个怎么实现比较好？

**Comment by mutouyun** [comment]
建议使用一条route，作为server向client发送消息的通路；
使用一条channel，作为client向server返回消息的通路。

重点在于，尽量将上行和下行流量分开，这样可以通过超时、重试等手段实现一些qos保证。
