### ISSUE TITLE
进程间大包传输报错了

### ISSUE THREAD

**Issue by WellsRevive** [mutouyun/cpp-ipc#8]
[find_storage] cc test failed: id = 30, cls_size = 3970496
fail: shm::handle for big message. msg_id: 180113, size: 3970449

最大消息传输限制多少？

**Comment by mutouyun** [comment]
3g的包？我对打包没做限制，报错是因为内存限制，不允许创建这么大的共享内存。
对于大共享内存创建失败的情况，会自动尝试分包发送，根据你的包大小，和ipc配置，性能上会慢一些

**Comment by WellsRevive** [comment]
传输3M的包，不是3g的包。尝试传输小包没有报错

**Comment by mutouyun** [comment]
大包处理默认对大于64bytes的包启用，你试试多大会报错。
这个错误一般是共享内存创建失败才会报。

**Comment by mutouyun** [comment]
报错只是个提示，如果报错，会自动拆包，每个包默认64bytes

**Comment by WellsRevive** [comment]
好的，非常感谢

**Comment by WellsRevive** [comment]
如果多一些接口说明和文档就更好了

**Comment by mutouyun** [comment]
已添加[全局常量定义](/mutouyun/cpp-ipc/wiki/全局常量定义)的说明。
