### ISSUE TITLE
你好，目前一条通道最多支持32个receiver，那么我如何获取当前已经创建的receiver数量

### ISSUE THREAD

**Issue by windowcc** [mutouyun/cpp-ipc#85]

**Comment by mutouyun** [comment]
有一个recv_count接口获取这个数量。
数量限制只在广播模式上有存在。

**Comment by windowcc** [comment]
class conn_head_base {
protected:
    std::atomic<cc_t> cc_{0}; // connections
    ipc::spin_lock lc_;
    std::atomic<bool> constructed_{false};
...
}
你好，我调试了代码。  发现当一个receiver异常退出之后。cc_变量对应的位没有被重置。还是1. 请问这个问题有好的解决方案吗？

**Comment by mutouyun** [comment]
有在recv的异常信号捕获里disconnect()嘛？
说实话现在的设计不够理想，主要是之前这个库的使用环境，是永不退出的常驻程序，崩溃重启也会彻底清理资源……
