### ISSUE TITLE
你好，请问在广播模式下，如何确保每一个receiver都可以接收到数据？

### ISSUE THREAD

**Issue by windowcc** [mutouyun/cpp-ipc#86]

**Comment by mutouyun** [comment]
服务端目前的机制是通过超时判断数据标记。
如果考虑到recv可能崩溃，服务端的超时就无法无限延长，因此理论上没有100%的方法保证每个recv都能收到数据，因为os可能一直不给某个recv调度时间片。
当然，实际上os没这么蠢，正常情况下设置合理的超时即可。

**Comment by windowcc** [comment]
谢谢
