### ISSUE TITLE
收取数据包时程序崩溃

### ISSUE THREAD

**Issue by sunyafeihit** [mutouyun/cpp-ipc#9]
您好，我在阅读了您的代码之后，认为比较比较适合我们公司的系统，所以使用您的程序收发一个比较大的数据包，单发多收。
我现在遇到一个问题是，收数据之后node会崩溃。
这是发数据的代码：
    ipc::route shm_send_ = ipc::route{"rslidar_packets_pkt"};  
    rslidar_msgs::rslidarScan scanMsg;
    ipc::buff_t outMsgBuf(&send_msg, sizeof(send_msg));
    shm_send_.send(outMsgBuf); 
收数据的代码是：
    ipc::route shm_recv_ = ipc::route{"rslidar_packets_pkt"};
    ipc::buff_t buf = shm_recv_.recv();
    auto recv_msg_ptr= buf.data<rslidar_msgs::rslidarScan>();       //方式1
   //TODO:how to get recv_msg_ptr type is from shm_recv.recv();
    rslidar_msgs::rslidarScan * recv_msg_ptr = static_cast<rslidar_msgs::rslidarScan * >(buf.data()); //方式2
通过方式1和方式2收取的数据都会崩溃，麻烦您问一下是什么原因呢？

**Comment by mutouyun** [comment]
确认一下，你的数据结构 **rslidar_msgs::rslidarScan** 的完整定义是什么样的？

**Comment by sunyafeihit** [comment]
您好，崩溃的原因找到了，那个数据结构里有vector，还有其他类。现在改成纯c的struct了，程序不再崩溃。
但是有另外两个问题，还向您请教一下：1. 同一个进程收发数据，数据是正确的，但是不同进程收到的数据有问题，我这个是点云，通过显示能看出来明显区别。2.收数据的频率一定要高于发数据的频率？不然内存占用会不断增加？我这边收数据频率低时过一会就收不到数据了。收数据会影响queue？多个进程读数据不会有问题吧？您的代码太高深，实在读起来困难。

谢谢您，麻烦了！




| |
sunyafeihit2017
邮箱：sunyafeihit2017@126.com
|

Signature is customized by Netease Mail Master

在2020年03月04日 12:29，木头云 写道：

确认一下，你的数据结构 rslidar_msgs::rslidarScan 的完整定义是什么样的？

**Comment by sunyafeihit** [comment]
不好意思，补充一下，我是在linux，ros中运行的，有没有过相关测试？可以使用吧？再次致谢




| |
sunyafeihit2017
邮箱：sunyafeihit2017@126.com
|

Signature is customized by Netease Mail Master

在2020年03月07日 15:08，sunyafeihit 写道：
您好，崩溃的原因找到了，那个数据结构里有vector，还有其他类。现在改成纯c的struct了，程序不再崩溃。
但是有另外两个问题，还向您请教一下：1. 同一个进程收发数据，数据是正确的，但是不同进程收到的数据有问题，我这个是点云，通过显示能看出来明显区别。2.收数据的频率一定要高于发数据的频率？不然内存占用会不断增加？我这边收数据频率低时过一会就收不到数据了。收数据会影响queue？多个进程读数据不会有问题吧？您的代码太高深，实在读起来困难。

谢谢您，麻烦了！




| |
sunyafeihit2017
邮箱：sunyafeihit2017@126.com
|

Signature is customized by Netease Mail Master

在2020年03月04日 12:29，木头云 写道：

确认一下，你的数据结构 rslidar_msgs::rslidarScan 的完整定义是什么样的？

**Comment by mutouyun** [comment]
1、正常情况下，channel并不会因为不同进程导致结果不同，你需要保证先序列化再发送。

2、收数据的频率当然要高于发数据的频率，共享内存不可能无限缓存你的消息，目前缓存区大小是255（个包），超出会被覆盖掉。我前几天新加了[全局常量定义](https://github.com/mutouyun/cpp-ipc/wiki/%E5%85%A8%E5%B1%80%E5%B8%B8%E9%87%8F%E5%AE%9A%E4%B9%89)的相关说明，其中关于`default_timeout`的描述中有说到这一点：若超出此时间队列仍然为满，则最早的数据包会被新数据覆盖（丢包）。

3、单写多读建议使用`route`，多写多读请使用`channel`。由于`route`不需要支持多对多，效率上会高一点。参考它们的定义：
```cpp
// #include "include/ipc.h"
using route   = chan<ipc::wr<relat::single, relat::multi, trans::broadcast>>;
using channel = chan<ipc::wr<relat::multi , relat::multi, trans::broadcast>>;
```
你可以用类似的方式定义自己的传输方案（比如单对单），功能越简单性能相对会越好。

4、正常来说，能编译过就可以尝试用。请参考[.travis.yml](https://github.com/mutouyun/cpp-ipc/blob/master/.travis.yml)中配置的基于linux的测试矩阵。
