### ISSUE TITLE
大数据公用的内存疑似存在数据被覆盖的情况

### ISSUE THREAD

**Issue by nepkira** [mutouyun/cpp-ipc#96]
我在项目中重度使用cpp-ipc传输数据，在使用mmb遇到了收到数据被覆盖的情况，使用情景如下：
1、修改过全局变量，大数据判断为8k以上，1MB对齐，8cache长度；
2、发送的数据都是3k-20k和一种固定100k的数据，数据内有校验信息，接收长度短于信息长度无法通过校验；
3、2个生产者以不同的但相对固定的频率发送消息，由于生产者间没有同步机制，不排除生产者同时发送的情况；
4、2个进程同时进行接收，由于项目的线程开得比较多，数据的响应处理时间有不及时的可能；

异常情况与对比如下：
1、使用一段时间会偶发性出现长度标识与buff_t的size对不齐的情况；
2、异常时，大概率出现情况1，数据内的长度信息是100k，而buff_t的size为8k-20k；
3、异常时，小概率出现情况2，数据内的长度信息不是100k，通不过校验；
4、异常时，可能一个接收者出现问题，也可能多个接收者出现问题；
5、单进程固定频率发送时不会出现异常；

我不认为是send失败或者超时清空，因为这样要么压根收不到，或者导致接收端掉线

主要疑问点：
id_pool位于共享内存上，在acquire时分配顺序是直接取上一个id+1；在release时是将id还给预分配变量；最后一个buff_t在析构的时候触发release；
但是我没有找到**分配时候一定确认预分配的id没有被分配出去**的逻辑，会不会出现下述情况：
* id0和id1接连被分配，由于调度问题，id1的释放被延迟了，这个间隔出现一次连续发送，id0和id1被相继分配；
* 在这种情况下，可能反复出现多个传输/处理指向id1指向的内存；
* 由于短数据覆盖长数据的情况可以通过校验，所以更多出现情况1。

当然不排除我看漏了

运行时候没有打印ipc库内的log，如果有需要可以补充，希望能解释下疑问点或提出建议，谢谢mutouyun！

**Comment by mutouyun** [comment]
可以在 def.h 中将 large_msg_limit 设置得很大，这样就会关闭大内存的缓存池，代价是大消息会分片传输，有比较大的性能问题。  
但可以通过这样的配置确认是不是 id_pool 分配回收导致的 bug。

**Comment by nepkira** [comment]
已经完全定位到产生数据的原因是以不同的传输方式打开了同一段共享内存，对此问题进行描述并关闭

现象：某个大数据公用内存只能分配一个相同的id，伴随库中自带的fifo满检测失效，并且传输过快的时候会产生数据覆盖；

原因：多进程场景下，未进行同步，对同一个话题以新的传输方式重新打开时，没有确认部分进程还没有destroy以释放共享内存，并且接收了部分新方式发送的消息

过程分析：
* 不同的传输方式下的传输头是不同的
* 当没有destroy时，共享内存不会释放，共享内存文件仍然存在，新方式的连接将直接使用原来的文件
* 当新发送一个消息，且接收者用不同的方式去接收这个消息的时候，数据将是错乱的
* 错乱的数据将有一定的概率将storage_成员误判为公用大内存信息，此时在buff_t析构时会对一个错乱id进行release
* id_pool的分配算法不支持判断未分配的id，且会导致后续的id分配出错（永远分配同一id），从而导致描述现象

结论：非bug，正常应用下，应该完全释放共享内存后，再以新方式打开同一话题，或者根本就不应该使用同一个话题

其他：可以在release中增加未分配判断，类似如下增强id分配的稳定性
```
for(auto check=cursor_;check!=max_count;check=next_[check])
{
   if(id==check)
  {
     ipc::log("id not acquire");
     return false;
  }
}
```
